### ISSUE TITLE
Bower lowercase "jquery" name now owned by the official jQuery repo

### ISSUE THREAD

**Issue by olivierphi** [components/jquery#41]
Hi!

Because of [this update](https://github.com/bower/bower/issues/1118), I haven't been able to install this shim component of Jquery, even with the lowercase name "jquery".
I had to update my "bower.json" file with this
`"jquery": "components/jquery#2.0.3"`
instead of
`jquery": "~2.0.0"`
, then clean my Bower local cache, in order to install your jQuery version.

Have you planned to choose a more explicit Bower name for this "component" version of jQuery, like "component-jquery"? This would avoid this type of issue :-)

**Comment by mgol** [comment]
> Is jQuery gonna provide composer and component(1) support too ?

The jQuery team will only maintain npm & bower support. If you need support for other package managers it needs to be handled by different repos like this one.
