### ISSUE TITLE
jQuery 3.7.1 Released

### ISSUE THREAD

**Issue by adrienmaloba** [components/jquery#72]
Hello,

https://blog.jquery.com/2023/08/28/jquery-3-7-1-released-reliable-table-row-dimensions

Thank you!

**Comment by marclaporte** [comment]
@RobLoach Please :-)

**Comment by RobLoach** [comment]
:heavy_check_mark:

**Comment by marclaporte** [comment]
Thank you but it's not appearing here: https://github.com/components/jquery/releases

FYI, the numbering pattern changed
https://packagist.org/packages/components/jquery#3.6.0
https://packagist.org/packages/components/jquery#v3.7.1

**Comment by RobLoach** [comment]
I'll throw another release tag in there. THanks.

@marclaporte Would you mind helping out with maintainership?

**Comment by adrienmaloba** [comment]
@RobLoach, thanks for the release!

**Comment by marclaporte** [comment]
> @marclaporte Would you mind helping out with maintainership?

Glad to help. And my colleague @adrienmaloba will help as well.

**Comment by marclaporte** [comment]
And @jonnybradley as well.

**Comment by marclaporte** [comment]
And @AngeloJMK as well.

**Comment by marclaporte** [comment]
@RobLoach

FYI:

The Tiki community recently switched to a Node.js build system for JavaScript and CSS dependencies:
https://dev.tiki.org/The-Tiki-27-plus-Build-System

However, we will continue to get these components from Packagist until March 2027 for Tiki 24x as it's a Long Term Support (LTS) version:
https://gitlab.com/tikiwiki/tiki/-/blob/24.x/vendor_bundled/composer.json
https://doc.tiki.org/Tiki24
